Repository wecode-bootcamp-korea/werecord-frontend, pull requests merged in 2021-06, with the labels that each got.

#1 [20기 이다슬] style: rending페이지 레이아웃/fade효과
  package-lock.json
  package.json
  public/images/login.png
  public/images/logo.png
  public/images/mainbackground.jpeg
  public/images/werecord.png
  public/images/기록합니다.png
  public/images/우리는.png
  src/Routes.js
  src/pages/Rending.js
Labels: Status: Accepted

#7 [20기 김수연] 모달 컴포넌트 : 모달 열림/닫힘 기능 구현
  src/components/Modal/Modal.js
  src/components/Modal/README.md
Labels: Status: 리뷰 요청

#6 [20기 이다슬] style: Mainpage 레이아웃, 현재 시간 받아오기 기능 완료
  public/images/fire.gif
  public/images/firewood.png
  src/Routes.js
  src/pages/Main.js
  src/pages/Rending.js
Labels: Status: 리뷰 요청

#3 [20기 전용민] Navbar 버튼별 클릭시 동작 기능 구현 (마이 페이지, 기수 페이지, 로그아웃 버튼)
  src/Routes.js
  src/components/Navbar.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#11 [20기 이다슬] 구글 소셜로그인 버튼 레이아웃, 로그인 구현
  package-lock.json
  package.json
  public/images/googleLogo.png
  public/index.html
  src/Routes.js
  src/pages/GoogleLogin.js
Labels: Status: 리뷰 요청

#2 [20기 김수연] refact : 리펙토링 중
  public/Data/BatchData.json
  public/images/Profile/ribon.png
  public/images/Profile/test1.jpeg
  public/images/run_cat.gif
  src/Routes.js
  src/components/Modal/Modal.js
  src/index.js
  src/pages/Batch/Batch.js
  src/pages/Batch/BestBatch/BestBatch.js
  src/pages/Batch/PeersBox/PeersBox.js
  src/pages/Batch/ProfileCard/ProfileCard.js
  src/pages/Batch/ProfileModal/ProfileModal.js
  src/pages/Util/checkObjData.js
Labels: Status: 리뷰 요청

#5 [20기 전용민]feat: 마이페이지 fetch 로직 구현 및 종택님 리뷰 반영 후 수정
  public/data/mypageInformationData.json
  src/Routes.js
  src/components/Modal/Modal.js
  src/pages/Mypage/Charts/BarChart.js
  src/pages/Mypage/Charts/LineChart.js
  src/pages/Mypage/EditForm.js
  src/pages/Mypage/Mypage.js
Labels: Status: 리뷰 요청

#8 [20기 김수연] 전체적인 리팩토링(useCallback 사용, 구조분해할당, state최소화 등)
  package-lock.json
  package.json
  src/pages/Batch/Batch.js
  src/pages/Batch/BestBatch/BestBatch.js
  src/pages/Batch/PeersBox/PeersBox.js
  src/pages/Batch/ProfileCard/ProfileCard.js
  src/pages/Batch/ProfileModal/ProfileModal.js
  src/pages/GoogleLogin.js
  src/pages/Main.js
  src/pages/Main/SendTimeModal/SendTimeModal.js
  src/pages/Rending.js
Labels: Status: 리뷰 요청

#16 [20기 김수연] fix : 모달 핸들함수 모달 내부에 구현으로 수정
  src/components/Modal/Modal.js
  src/components/Modal/README.md
Labels: Status: 리뷰 요청

#17 [20기 김수연] Feature/batch page 리펙토링 및 기능 개선
  src/pages/Batch/BestBatch/BestBatch.js
  src/pages/Batch/PeersBox/PeersBox.js
  src/pages/Batch/ProfileCard/ProfileCard.js
  src/pages/Batch/ProfileModal/ProfileModal.js
  src/pages/Main.js
Labels: Status: 리뷰 요청

#13 [20기 김수연] myPage 회원정보 수정 기능 구현 완료
  src/pages/Mypage/EditForm.js
  src/pages/Mypage/Mypage.js
Labels: Status: 리뷰 요청

#15 [20기 이다슬] 구글 소셜로그인, 추가 정보 입력 모달 백엔드 통신기능 완료, 추가입력 모달 UI 기능 수정중
  src/Routes.js
  src/components/Navbar.js
  src/config.js
  src/pages/Rending.js
  src/pages/Rending/LoginSigninModal/GoogleLogin.js
  src/pages/Rending/LoginSigninModal/LoginModal.js
  src/pages/Rending/LoginSigninModal/SignInModal.js
  src/pages/Rending/Rending.js
Labels: Status: 리뷰 요청

#10 [20기 전용민] feat: Mentor페이지 슬라이더, 기수 추가 기능 구현
  public/data/MentorPageData.json
  src/Routes.js
  src/components/Navbar.js
  src/config.js
  src/pages/MentorPage/DeleteBatchInfoForm.js
  src/pages/MentorPage/EditBatchInfoForm.js
  src/pages/MentorPage/EditMentorInfoForm.js
  src/pages/MentorPage/IMAGES.js
  src/pages/MentorPage/MakeBatchForm.js
  src/pages/MentorPage/MentorPage.js
Labels: Status: 리뷰 요청
